name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs: 
    lint:
      name: Lint
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - name: Set up Go
          uses: actions/setup-go@v4
          with:
            go-version: '1.24.1'
            cache: true

        - name: Install golangci-lint
          run: |
            curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.2

        - name: Run golangci-lint
          run: golangci-lint

    test:
      name: Test
      runs-on: ubuntu-latest
      needs: 
        - lint
      steps:
        - uses: actions/checkout@v4

        - name: Set up Go
          uses: actions/setup-go@v4
          with:
            go-version: '1.24.1'
            cache: true

        - name: Install dependencies
          run: go mod download

        - name: Run tests
          run: go test -v -race ./...
    